2

diff --git a/raemisDBbackup b/raemisDBbackup
--- a/raemisDBbackup
+++ b/raemisDBbackup
@@ -2,7 +2,7 @@
 #!/bin/bash
 ##################################################################################################
 # Params    *  $1 - DB directorie on Raemis * $2 - DB  filename * $3- backup Directory on Nicita #
-#           *                                                                                                                           *                                                                         $
+#           *                                                                                                                           *                                                                               *                                #
 # defaults  *         /usr/share/raemis/db/ *    raemis.db      *   /home/bscell/backups         #
 ##################################################################################################
 
@@ -11,7 +11,7 @@
 if [ "$#" -ne 3 ]
   then
                 echo "Wrong number of parameters recieved "
-                origdir="/usr/share/raemis/db/"
+                origdir="/usr/share/raemis/db"
                 dbfilename="raemis.db"
           backupdir="/home/bscell/backups"
 
@@ -30,15 +30,18 @@ fi
 
 ####################check locations and file#####################################################
 
-ssh root@raemis [ -d "$origdir" ] && echo "Directory $origdir OK." || { echo "Error: Directory $origdir  at Raemis not reachable." ;  exit 1; }
-ssh root@raemis [ -f "$origdir/$dbfilename" ] && echo "DBfile  $dbfilename ok." || { echo "Error: DBfile $dbfilename  not reachable." ;  exit 1; }
+ssh root@raemis [ -d "$origdir" ]  && echo "Directory $origdir OK." || { echo "Error: Directory $origdir  at Raemis not reachable." ;  exit 1; } ;
+
+ssh root@raemis [ -f "$origdir/$dbfilename" ]  && echo "DBfile  $dbfilename ok." || { echo "Error: DBfile $dbfilename  not reachable." ;  exit 1; } ;
+
 [ -d "$backupdir" ] && echo "Directory $backupdir  OK." || { mkdir $backupdir  && echo "Warning: Creating Directory $backupdir ." || exit 1; }
-
-#################################create and transfer backup #############################
-
-bfilename="RaemisDB_$(date +"%m%d%y_%k%M")"
- scp root@raemis:$origdir/$dbfilename $backupdir/$bfilename && echo "Succes: File "$bfilename" copied."  || { echo "Error: Failed to copy file " ; exit 1; }
- gzip -f  "$backupdir/$bfilename" && echo "Succes: File "$bfilename" archived. "  || { echo "Error: Failed to archive file "$bfilename""  ; exit 1; }
+echo $HOME/$backupdir
+################################create and transfer backup #############################
+bfilename="RaemisDB_$(date +"%m%d%y%H%M")"
+#echo " root@raemis:${origdir}/${dbfilename} ${backupdir}/${bfilename}"
+ scp root@raemis:${origdir}/${dbfilename} ${backupdir}  && echo "Succes: File "$dbfilename" copied."  || { echo "Error: Failed to copy file " ; exit 1; }
+ gzip -f  "$backupdir/$dbfilename" && echo "Succes: File "$dbfilename" archived. "  || { echo "Error: Failed to archive file "$bfilename""  ; exit 1; }
+mv "$backupdir/${dbfilename}.gz"  "$backupdir/${bfilename}.gz"
 ###################################################remove old archive ( older than 14 days )###########################
 echo "Checking for Old files to remove " ;find "$backupdir" -type f -name 'RaemisDB_*' -mtime 14  -exec rm {} \;
 exit 0
